apiVersion: 1

datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false

  - name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false

  - name: sweetcorn
    type: jaeger
    access: proxy
    url: http://sweetcorn:13579/jaeger
    basicAuth: false
    isDefault: true
